
const messages : {[key:string] : any} = {
  en: {
    start: "Enter the start date",
    end: "Enter the end date",
    title: "Time differnce",
    result_m: "In months: {time}",
    result_d: "In days: {time}",
    result_h: "In hours: {time}",
    result_t: "In total: {months} {months, plural, one{month}other{months}}, {days} {days, plural, one{day} other{days}} and {hours} {hours, plural, one{hour} other{hours}}",
    err: "The end date must be after the starting date",
    info: "Info",
    support: "Support",
    marketing: "Marketing",
    tou: "Terms of Use",
    privacy: "Privacy Policy",
    menu: "Menu",
    sub: "Submenu"
  },
  et: {
    start: "Sisesta algus kuupäev",
    end: "Sisesta lõpu kuupäev",
    title: "Ajavahe",
    result_m: "Kuudes: {time}",
    result_d: "Päevades: {time}",
    result_h: "Tundides: {time}",
    result_t: "Kokku: {months} {months, plural, one{kuu}other{kuud}}, {days} {days,plural,one{päev} other{päeva}} ja {hours} {hours, plural, one{tund} other{tundi}}",
    err: "Lõppkuupäev peab olema peale algkuupäeva",
    info: "Info",
    support: "Toetus",
    marketing: "Turundus",
    tou: "Kasutustingimused",
    privacy: "Privaatsuspoliitika",
    menu: "Menüü",
    sub: "Alammenüü"
  },
  ru: {
    start: "Введите дату начала",
    end: "Введите дату окончания",
    title: "Разница во времени",
    result_m: "В месяцах: {time}",
    result_d: "В днях: {time}",
    result_h: "В часах: {time}",
    result_t: "В итоге: {months} {months, plural, one{месяц} other{месяца}}, {days} {days,plural,one{день} other{дней}} и {hours} {hours,plural, one{час} other{часов}}",
    err: "Дата окончания должна быть позже даты начала.",
    info: "Информация",
    support: "Поддержка",
    marketing: "Маркетинг",
    tou: "Условия эксплуатации",
    privacy: "Политика конфиденциальности",
    menu: "Меню",
    sub: "Подменю"
  },
  de: {
    start: "Geben Sie das Startdatum ein",
    end: "Geben Sie das Enddatum ein",
    title: "Zeitunterschied",
    result_m: "In Monaten: {time}",
    result_d: "In Tagen: {time}",
    result_h: "In Stunden: {time}",
    result_t: "Insgesamt: {months} {months,plural, one{Monat} other{Monaten}}, {days} {days,plural, one{Tag} other{Tagen}} und {hours} {hours, plural, one{Stunde} other{Stunden}}",
    err: "Das Enddatum muss nach dem Startdatum liegen",
    info: "Die Info",
    support: "Unterstützung",
    marketing: "Marketing",
    tou: "Nutzungsbedingungen",
    privacy: "Datenschutz-Bestimmungen",
    menu: "Speisekarte",
    sub: "Untermenü"
  },
  lt: {
    start: "Įveskite pradžios datą",
    end: "Įveskite pabaigos datą",
    title: "Laiko skirtumas",
    result_m: "Per mėnesius: {time}",
    result_d: "Per dienas: {time}",
    result_h: "Per valandas: {time}",
    result_t: "Iš viso: {months} {months,plural, one{mėnuo} other{mėnesių}}, {days} {days, plural, one{dieną} other{dienų}} ir {hours} {days,plural, one{valandą} other{valandų}}",
    err: "Pabaigos data turi būti vėlesnė nei pradžios data",
    info: "Informacija",
    support: "Palaikymas",
    marketing: "Rinkodara",
    tou: "Naudojimo sąlygos",
    privacy: "Privatumo politika",
    menu: 'Meniu',
    sub: "Submeniu"
  }
};

export default messages
